# SPDX-FileCopyrightText: Copyright (c) 2019-2025 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
docker:
  image: yegor256/ruby
install: |-
  sudo /usr/bin/install-node.sh
  sudo npm install -g grunt
  sudo apt-get update && sudo apt-get install firefox
merge:
  script: |-
    npm ci
    grunt --port=4000 --monochrome
