# SPDX-FileCopyrightText: Copyright (c) 2019-2025 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
docker:
  image: yegor256/ruby
install: |-
  sudo /usr/bin/install-node.sh
merge:
  script: |-
    npm ci
    npm install -g grunt
    grunt --port=4000 --monochrome
